export const FETCH_SHOTS = 'FETCH_SHOTS';
export const RECEIVE_FETCH_SHOTS = 'RECEIVE_FETCH_SHOTS';
export const FETCH_SHOT_ID = 'FETCH_SHOT_ID';
export const RECEIVE_FETCH_SHOT_ID = 'RECEIVE_FETCH_SHOT_ID';

export const FETCH_FAILED = 'FETCH_FAILED';
